### ISSUE TITLE
List items not permitted outside ul, ol or menu elements

### ISSUE THREAD

**Issue by tad-lispy** [Lori2Lori/personal-website#4]
Hey! Congratulations on fixing and closing your first issue!

Since it went so smoothly here is another one for you to fix.

Please take a look at [Mozilla's HTML reference for `li` elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li), especially _Permitted parent elements_ in a pink box at the beginning.

Please try to figure it out yourself. If it won't be clear to you after reading the article linked above then do not hesitate to ask. Good luck!

**Comment by Lori2Lori** [comment]
Thanks, I've fixed it today.
